version = 0.1

[default.deploy.parameters]
stack_name = "cover-letter-builder"
resolve_s3 = true
s3_prefix = "cover-letter-builder"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "ap-southeast-2"
